[wokwi]
version = 1
elf = ".pio/build/wemos_s3_mini_DEBUG/firmware.elf"
firmware=".pio/build/wemos_s3_mini_DEBUG/firmware.bin"

diagram = "diagram.json"

[[pins]]
name = "A3"
number = 3
mode = "analog"

[[pins]]
name = "2"
number = 2
mode = "output"

[[pins]]
name = "5"
number = 5
mode = "output"

[[pins]]
name = "0"
number = 0
mode = "input"

[[pins]]
name = "4"
number = 4
mode = "output"

[[pins]]
name = "1"
number = 1
mode = "output"

[[pins]]
name = "21"
number = 21
mode = "output"

[[pins]]
name = "20"
number = 20
mode = "input"

[[pins]]
name = "8"
number = 8
mode = "input"

[[pins]]
name = "10"
number = 10
mode = "output"

[[pins]]
name = "7"
number = 7
mode = "input"

[[pins]]
name = "6"
number = 6
mode = "input"

[env]
WIFI_SSID = "***REMOVED***"
WIFI_PASSWORD = "***REMOVED***" 