#include "stateMachine.h"

IdleStateMachine idleState;
WaitForTemperatureStateMachine waitForTemperatureState;
PreparingStateMachine preparingState;
WaitForTimerStateMachine timerState;
ConfirmStateMachine confirmState;
TuningStateMachine tuningState;