#!/usr/bin/env node
// recipe-stress.mjs — reproducer for "BLE drops when opening a recipe".
//
// The story: the firmware-side fix in PR #14 deferred command dispatch
// from the NimBLE host task to the main-loop task, then guarded the
// pending slot with `if (_hasPendingCommand) return;` — a silent drop
// on overlap. This probe exercises the same path against the sim
// bridge to see whether (a) a fresh recipe load round-trip completes
// cleanly and (b) sending two recipe loads back-to-back triggers the
// "command dropped: previous still queued" warning.
//
// Usage:
//   node tools/sim-probe/recipe-stress.mjs
//   node tools/sim-probe/recipe-stress.mjs --url ws://localhost:8765
//
// The bridge must already be running:
//   cd tools/sim-bridge && npm start

const args = process.argv.slice(2);
let url = 'ws://localhost:8765';
for (let i = 0; i < args.length; i++) {
    if (args[i] === '--url') { url = args[++i]; continue; }
}

// Build a recipe big enough to force chunked notify on a real link
// (negotiated MTU is typically 23..185 bytes — the ESP32 firmware
// chunks payloads accordingly). The sim emits one JSON-per-line over
// stdout so chunking doesn't matter there, but the response size still
// stresses the host buffers + the dispatch deferral.
function bigRecipe(lines = 80) {
    const out = [];
    out.push('# stress recipe — generated by recipe-stress.mjs');
    for (let i = 0; i < lines; i++) {
        const t = 60 + (i % 30);
        out.push(`SET_TEMP ${t}`);
        out.push(`WAIT_TEMP ${t}`);
        out.push(`HOLD ${5 + (i % 10)}`);
    }
    out.push('STOP');
    return out.join('\n');
}

const FILE       = 'stress.txt';
const REQ_TIMEOUT = 5_000;

const ws = new WebSocket(url);
const pending = new Map();
let nextRid = 1;
let failed = 0;

function send(type, extra = {}) {
    return new Promise((resolve, reject) => {
        const rid = `r${nextRid++}`;
        const timer = setTimeout(() => {
            pending.delete(rid);
            reject(new Error(`timeout (${REQ_TIMEOUT}ms) waiting for ${type} rid=${rid}`));
        }, REQ_TIMEOUT);
        pending.set(rid, { resolve, reject, timer, type });
        ws.send(JSON.stringify({ tp: type, rid, ...extra }));
    });
}

function pad(s, n) { return (s + ' '.repeat(n)).slice(0, n); }

function assert(label, cond, detail = '') {
    if (cond) console.log(`[probe] ✓ ${label}${detail ? `  ${detail}` : ''}`);
    else      { console.error(`[probe] ✗ ${label}${detail ? `  ${detail}` : ''}`); failed++; }
}

ws.addEventListener('open', async () => {
    console.log(`[probe] connected ${url}`);
    const content = bigRecipe();
    console.log(`[probe] recipe size: ${content.length} bytes`);

    try {
        // ── 1. seed the recipe on the in-memory SD ─────────────
        const save = await send('req:recipe:save', { file: FILE, content });
        assert('save', save.tp === 'res:ok');

        // ── 2. listRecipes returns the seeded file ─────────────
        const list = await send('req:recipe:list');
        console.log(`[probe] list raw: ${JSON.stringify(list)}`);
        assert('list.tp', list.tp === 'res:recipe:list');
        assert('list contains file', Array.isArray(list.recipes) && list.recipes.includes(FILE),
               `recipes=${JSON.stringify(list.recipes)}`);
        // Re-fire after a 200 ms gap in case there's a write-back lag
        await new Promise(r => setTimeout(r, 200));
        const list2 = await send('req:recipe:list');
        console.log(`[probe] list raw (after 200ms): ${JSON.stringify(list2)}`);

        // ── 3. single load — golden path ───────────────────────
        const load1 = await send('req:recipe:load', { file: FILE });
        assert('load.tp',      load1.tp === 'res:recipe:load');
        assert('load.file',    load1.file === FILE);
        assert('load.content roundtrip',
               typeof load1.content === 'string' && load1.content.length === content.length,
               `got ${load1.content?.length ?? '?'}, expected ${content.length}`);

        // ── 4. burst: 5 loads with no `await` between sends ────
        //     If `_pendingCommand`'s single-slot guard silently drops
        //     overlapping commands, some of these will time out.
        console.log('[probe] burst: 5 back-to-back loads');
        const t0 = Date.now();
        const burst = await Promise.allSettled(
            Array.from({ length: 5 }, () => send('req:recipe:load', { file: FILE }))
        );
        const fulfilled = burst.filter(r => r.status === 'fulfilled').length;
        const rejected  = burst.filter(r => r.status === 'rejected');
        assert(`burst: all 5 responded (got ${fulfilled})`, fulfilled === 5);
        for (const r of rejected) {
            console.error(`[probe]    rejected: ${r.reason?.message ?? r.reason}`);
        }
        console.log(`[probe]    burst elapsed: ${Date.now() - t0}ms`);

        // ── 5. cleanup ─────────────────────────────────────────
        const del = await send('req:recipe:delete', { file: FILE });
        assert('delete', del.tp === 'res:ok');
    } catch (e) {
        console.error('[probe] fatal:', e.message);
        failed++;
    }

    ws.close();
    process.exit(failed === 0 ? 0 : 1);
});

ws.addEventListener('message', (e) => {
    let data;
    try { data = JSON.parse(e.data); }
    catch { return; }
    if (data.rid && pending.has(data.rid)) {
        const p = pending.get(data.rid);
        pending.delete(data.rid);
        clearTimeout(p.timer);
        if (data.tp === 'res:error') p.reject(new Error(data.err || 'res:error'));
        else                          p.resolve(data);
    }
});

ws.addEventListener('error', (e) => {
    console.error('[probe] WebSocket error:', e?.message ?? e);
    process.exit(2);
});

ws.addEventListener('close', () => {
    if (pending.size > 0) {
        for (const [rid, { type }] of pending) {
            console.error(`[probe] ✗ ${type} (rid=${rid}) connection closed before response`);
            failed++;
        }
        process.exit(failed === 0 ? 0 : 1);
    }
});
