name: PlatformIO CI

on:
  push:
    tags:
      - "*" # Trigger only on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""

          draft: false
          prerelease: false

  upload:
    runs-on: ubuntu-latest
    needs: [build, publish]
    strategy:
      matrix:
        env: [wemos_s3_mini]
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.env }}
          path: .pio/build/${{ matrix.env }}
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./${{ matrix.env }}
          mv .pio/build/${{ matrix.env }}/firmware.bin ./${{ matrix.env }}/${{ matrix.env }}.bin
          mv .pio/build/${{ matrix.env }}/bootloader.bin ./${{ matrix.env }}/${{ matrix.env }}-bootloader.bin
          mv .pio/build/${{ matrix.env }}/firmware.elf ./${{ matrix.env }}/${{ matrix.env }}.elf
          mv .pio/build/${{ matrix.env }}/partitions.bin ./${{ matrix.env }}/${{ matrix.env }}-partitions.bin
          gh release upload ${{ github.ref_name }} ${{ matrix.env }}/*

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [wemos_s3_mini]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Get cached build
        uses: actions/cache@v4
        with:
          path: .pio/build
          key: ${{ matrix.env }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.env }}-${{ github.sha }}

      - name: Build for ${{ matrix.env }}
        run: pio run -e ${{ matrix.env }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.env }}
          path: .pio/build/${{ matrix.env }}
