name: PlatformIO CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [wemos_s3_mini]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build for ${{ matrix.env }}
        run: pio run -e ${{ matrix.env }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.env }}
          path: .pio/build/${{ matrix.env }}
          overwrite: true
          include-hidden-files: true
