name: PlatformIO CI

on:
  push:
    tags:
      - "*" # Trigger only on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""

          draft: false
          prerelease: false

  upload:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        env: [wemos_s3_mini]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.env }}
          path: .pio/build/${{ matrix.env }}
      - name: Upload artifacts to releases
        run: |
          gh release upload ${{ github.ref }} .pio/build/${{ matrix.env }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [wemos_s3_mini]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build for ${{ matrix.env }}
        run: pio run -e ${{ matrix.env }}

      - name: Get release info
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.split('/').pop();
            const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag
            });
            return release.data.upload_url;
      - name: Upload artifacts to releases
        run: |
          gh release upload ${{ steps.create_release.outputs.upload_url }} .pio/build/${{ matrix.env }}
